server:
  port: 8081

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}

azure:
  storage:
    container:
      media: ${MEDIA_CONTAINER}
      profile: ${PROFILE_CONTAINER}

spring:
  mail:
    host: ${SMTP_SERVER}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          from: ${SMTP_FROM}
          auth: true
          starttls:
            enable: true
          ssl:
            trust: ${SMTP_SERVER}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: LISTING-SERVICE
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org:
      springframework:
        security: DEBUG
